env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
plugins:
  - 'import'
  - '@typescript-eslint'
rules:
  import/order: 'warn'
